config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :sessions,
    controllers: {registrations: "users",
                  sessions: "sessions",
                  omniauth_callbacks: "omniauth_callbacks"}
  as :user do
    get "login", to: "sessions#new", as: :new_user_session
    post "login", to: "sessions#create", as: :user_session
    delete "logout", to: "devise/sessions#destroy", as: :destroy_user_session
  end
  root "static_pages#home"
  get "/fetch_items", to: "products#filter_product", as: "fetch_items"
  resources :categories
  resources :products, only: %i(index show) do
    resources :comments
    resources :ratings, only: :create
    collection do
      match "search" => "products#index", via: [:get, :post], as: :search
    end
  end
  resources :orders do
    resources :order_details, only: :index
  end
  namespace :admin do
    root "static_pages#home"
    resources :users
    resources :categories do
      resources :products
    end
    resources :products
    resources :orders do
      resources :order_details
    end
  end
  resources :carts, only: :index
  get "add_cart/:id_product", to: "carts#add_cart", as: :add_cart
  get "remove_cart/:id_product", to: "carts#remove_cart", as: :remove_cart
  put "orders/:id_order", to: "orders#cancel", as: :cancel
  put "update_hard_cart", to: "carts#update_hard_cart", as: :update_hard_cart
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details
  has_many :products, through: :order_details

  enum status: %i(in_progress cancelled rejected approved)
  validates :name, :phone, :address, presence: true

  delegate :name, to: :user, prefix: :user
  delegate :phone, to: :user, prefix: :user
  delegate :address, to: :user, prefix: :user

  scope :status, ->(status){where status: status if status}
  scope :newest, ->{order(created_at: :desc)}

  validate :order_details_present

  def order_details_present
    errors.add(:order, t("error_message")) if order_details.nil?
  end
end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < AdminController
    load_and_authorize_resource

    def index
      @orders = Order.status(params[:status])
        .paginate page: params[:page], per_page: Settings.product_per_page
    end

    def update
      ActiveRecord::Base.transaction do
        begin
          if @order.send("#{params[:order][:status]}!")
            flash[:danger] = t "sucess_msg"
            redirect_to admin_orders_path
          end
        rescue
          flash[:danger] = t "error_message"
          render :index
        end
      end
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_order, only: :cancel
  before_action :load_orders, only: %i(cancel index)
  before_action :check_cart_empty, only: :create
  before_action :current_cart, :quantity_in_cart, only: %i(new create)
  before_action :logged_in_user

  include OrdersHelper

  def index; end

  def new
    @order = Order.new
  end

  def create
    ActiveRecord::Base.transaction do
      @order = Order.new order_params
      if @order.save
        create_ordersdetails session[:cart], @order
        UserMailer.order_mail(current_user, @order).deliver_now
        create_order_success
      end
    end
  rescue
    flash[:danger] = t "order_fail"
    render :new
  end

  def cancel
    ActiveRecord::Base.transaction do
      @order.cancelled!
      OrderMailer.cancel_order(current_user, @order).deliver_now
      rollback_quantity @order
      respond_to do |format|
        format.json {}
        format.js {}
      end
    end
  rescue
    flash[:danger] = "cancel_failed"
    render :index
  end

  private

  def order_params
    params.require(:order).permit :user_id, :total, :name, :phone, :address
  end

  def redirect_if_cart_empty
    flash[:danger] = t "empty_cart"
    redirect_to carts_path
  end

  def find_order
    @order = Order.find_by id: params[:id_order]
    valid_object @order
  end

  def rollback_quantity order
    order.order_details.each do |detail|
      detail.product.increment!(:quantity, detail.quantity) if detail.persisted?
    end
  end

  def load_orders
    @orders = current_user.orders.newest
      .paginate page: params[:page], per_page: Settings.paginate.per_page
  end

  def check_cart_empty
    return redirect_if_cart_empty if (session[:cart].empty? || session[:cart].size == Settings.quantity.zero)
  end

  def create_order_success
    flash[:success] = t "success_msg"
    session[:cart] = {}
    redirect_to root_path
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def create_ordersdetails cart, order
    producs_of_current_cart = Product.load_product_by_ids cart.keys
    producs_of_current_cart.each do |product|
      product.quantity_in_cart = cart[product.id.to_s]
      unit_price = (product.price).to_i
      total_price = product.quantity_in_cart * unit_price
      order_detail = order.order_details.new(order_id: order.id,
        product_id: product.id, quantity: product.quantity_in_cart,
        unit_price: unit_price, total_price: total_price)
      order_detail.save
    end
  end
end

app/views/admin/orders/_order_row.html.erb
<tr id="order-<%= order.id %>">
  <td><%= create_index_row params[:page], order_counter, Settings.product_per_page %></td>
  <td><%= order.user_name %></td>
  <td><%= order.status %></td>
  <td><%= link_to t("orders.view_link"), admin_order_order_details_path(order.id) %></td>
  <td class="clearfix d-flex">
    <% if order.in_progress? %>
      <%= form_for [:admin, order], remote: true do |f| %>
        <%=  f.hidden_field :status, value: Order.statuses.key(3) %>
        <%= f.submit t("orders.accept"), class: "btn btn-primary" %>
      <% end %>

      <%= form_for [:admin, order], remote: true do |f| %>
        <%=  f.hidden_field :status, value: Order.statuses.key(2) %>
        <%= f.submit t("orders.reject"), class: "btn btn-danger" %>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/admin/orders/_orders.html.erb
<table class="table table-striped table-hover table-list">
  <thead class="thead-dark">
    <tr>
      <th><%= t "orders.id" %></th>
      <th><%= t "name" %></th>
      <th><%= t "orders.status" %></th>
      <th><em class="fa fa-cog"></em></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
     <%= render partial: "order_row", collection: @orders, as: :order %>
  </tbody>
</table>

app/views/admin/orders/index.html.erb
<h1><%= t "orders.title" %></h1>
<div class="panel panel-default panel-table">
  <div class="panel-body order-items">
      <%= render "orders", collection: @orders %>
  </div>
  <div class="panel-footer">
    <div class="row">
      <div class="col col-xs-8">
        <%= will_paginate @orders %>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/update.js.erb
$('.order-items').html('<%= escape_javascript(render "admin/orders/orders") %>');