config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :sessions,
    controllers: {registrations: "users",
                  sessions: "sessions",
                  omniauth_callbacks: "omniauth_callbacks"}
  as :user do
    get "login", to: "sessions#new", as: :new_user_session
    post "login", to: "sessions#create", as: :user_session
    delete "logout", to: "devise/sessions#destroy", as: :destroy_user_session
  end
  root "static_pages#home"
  get "/fetch_items", to: "products#filter_product", as: "fetch_items"
  resources :categories
  resources :products, only: %i(index show) do
    resources :comments
    resources :ratings, only: :create
    collection do
      match "search" => "products#index", via: [:get, :post], as: :search
    end
  end
  resources :orders do
    resources :order_details, only: :index
  end
  namespace :admin do
    root "static_pages#home"
    resources :users
    resources :categories do
      resources :products
    end
    resources :products
    resources :orders do
      resources :order_details
    end
  end
  resources :carts, only: :index
  get "add_cart/:id_product", to: "carts#add_cart", as: :add_cart
  get "remove_cart/:id_product", to: "carts#remove_cart", as: :remove_cart
  put "orders/:id_order", to: "orders#cancel", as: :cancel
  put "update_hard_cart", to: "carts#update_hard_cart", as: :update_hard_cart
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  belongs_to :user, optional: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart
  before_action :find_product, except: :index
  before_action :current_cart, :quantity_in_cart, only: :index

  def index; end

  def add_cart
    if session[:cart].key?(@product.id.to_s)
      session[:cart][@product.id.to_s] += Settings.quantity.default
    else
      session[:cart][@product.id.to_s] = Settings.quantity.default
    end
    update_decrement_product_quantity Settings.quantity.default
    respond_to do |format|
      format.html{render "static_pages/home"}
      format.json {}
      format.js
    end
  end

  def remove_cart
    if session[:cart].key?(@product.id.to_s)
      update_increment_product_quantity session[:cart][@product.id.to_s]
      session[:cart].delete @product.id.to_s
    end
    redirect_to carts_path
  end

  def update_hard_cart
    return render_validate_fail unless validate_quantity_cart @product,
      params[:quantity].to_i, true
    return return_quantity_is_zero if params[:quantity].to_i < Settings.quantity.default
    if session[:cart].key?(@product.id.to_s)
      current_quantity = session[:cart][@product.id.to_s]
      if current_quantity > params[:quantity].to_i
        update_increment_product_quantity current_quantity - params[:quantity].to_i
      elsif current_quantity < params[:quantity].to_i
        update_decrement_product_quantity params[:quantity].to_i - current_quantity
      end
      session[:cart][@product.id.to_s] = params[:quantity].to_i
    end
    redirect_to carts_path
  end

  private

  def validate_quantity_cart product, quantity, update_hard = false
    if update_hard || !session[:cart].key?(@product.id.to_s)
      product.quantity >= quantity
    else
      product.quantity >= (quantity + session[:cart][@product.id.to_s])
    end
  end

  def render_validate_fail
    flash[:danger] = t ".validate_quantity_fail"
    redirect_to carts_path
  end

  def return_quantity_is_zero
    flash[:danger] = t ".validate_quantity_is_zero"
    redirect_to carts_path
  end

  def find_product
    @product = Product.find_by id: params[:id_product]
    valid_object @product
  end

  def update_decrement_product_quantity quantity
    @product.decrement!(:quantity, quantity)
  end

  def update_increment_product_quantity quantity
    @product.increment!(:quantity, quantity)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def set_cart
    session[:cart] ||= {}
  end

  def sum_total_price_of_cart
    @producs_of_current_cart.collect{|product| product.quantity_in_cart * product.price}.sum
  end

  def is_empty_cart?
    session[:cart].blank?
  end
end

app/views/carts/_cart_item.html.erb
<tr>
  <td data-th="Product">
    <div class="row">
      <div class="col-sm-10">
        <h4 class="nomargin"><%= product.name %></h4>
      </div>
    </div>
  </td>
  <td data-th="Price" class="price"><%= number_to_currency product.price %></td>
  <td data-th="Quantity">
    <input type="number" class="form-control text-center quantity"
      min="<%= Settings.quantity.default %>" max="<%= product.quantity %>"
      value="<%= product.quantity_in_cart %>" data-product="<%= product.id %>">
  </td>
  <td data-th="Subtotal" class="text-center subtotal">
    <%= number_to_currency(product.price * product.quantity_in_cart) %>
  </td>
  <td class="actions" data-th="" class="unit_price">
    <%= link_to remove_cart_path(product), id: "destroy-product",
      "data-href": remove_cart_path(product), class: "btn btn-danger btn-sm" do %>
        <i class="fa fa-trash"></i>
    <% end %>
  </td>
</tr>
<%= javascript_include_tag "cart" %>

app/views/carts/add_cart.js.erb
$('.shopping-cart').html('<%= escape_javascript(render 'layouts/cart_text') %>');

app/views/carts/index.html.erb
<h1><%= t "shopping_cart" %></h1>
<table id="cart" class="table table-hover table-condensed">
  <thead>
    <tr>
      <th class="w-50"><%= t ".product" %></th>
      <th class="w-10"><%= t ".price" %></th>
      <th class="w-8"><%= t ".quantity" %></th>
      <th class="w-22 text-center"><%= t ".subtotal" %></th>
      <th class="w-10"></th>
    </tr>
  </thead>
  <tbody>
      <%= render partial: "cart_item", collection: @producs_of_current_cart, as: :product %>
  </tbody>
  <tfoot>
    <tr>
      <td>
        <%= link_to products_path, class: "btn-accent add-to-card" do %>
          <i class="fa fa-angle-left"></i> <%= t ".continue_shopping" %>
        <% end %>
      </td>
      <% unless session[:cart].size > Settings.quantity.zero %>
        <td colspan="2" class="hidden-xs">There are no items in this cart</td>
      <% end %>
      <td class="total_price">
        <% unless session[:cart].empty? || session[:cart].size == Settings.quantity.zero %>
          <span><%= t ".total" %></span>
          <%= number_to_currency sum_total_price_of_cart %>
        <% end %>
      </td>
      <td>
        <% unless session[:cart].empty? || session[:cart].size == Settings.quantity.zero %>
          <%= link_to new_order_path(current_user), class: "btn btn-success" do %>
            <%= t ".checkout" %> <i class="fa fa-angle-right"></i>
          <% end %>
        <% end %>
      </td>
    </tr>
  </tfoot>
</table>