config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :sessions,
    controllers: {registrations: "users",
                  sessions: "sessions",
                  omniauth_callbacks: "omniauth_callbacks"}
  as :user do
    get "login", to: "sessions#new", as: :new_user_session
    post "login", to: "sessions#create", as: :user_session
    delete "logout", to: "devise/sessions#destroy", as: :destroy_user_session
  end
  root "static_pages#home"
  get "/fetch_items", to: "products#filter_product", as: "fetch_items"
  resources :categories
  resources :products, only: %i(index show) do
    resources :comments
    resources :ratings, only: :create
    collection do
      match "search" => "products#index", via: [:get, :post], as: :search
    end
  end
  resources :orders do
    resources :order_details, only: :index
  end
  namespace :admin do
    root "static_pages#home"
    resources :users
    resources :categories do
      resources :products
    end
    resources :products
    resources :orders do
      resources :order_details
    end
  end
  resources :carts, only: :index
  get "add_cart/:id_product", to: "carts#add_cart", as: :add_cart
  get "remove_cart/:id_product", to: "carts#remove_cart", as: :remove_cart
  put "orders/:id_order", to: "orders#cancel", as: :cancel
  put "update_hard_cart", to: "carts#update_hard_cart", as: :update_hard_cart
end

app/models/product.rb
class Product < ApplicationRecord
  acts_as_paranoid
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
  attr_accessor :quantity_in_cart
  belongs_to :category
  has_many :order_details
  has_many :orders, through: :order_details
  has_many :ratings, dependent: :destroy
  has_many :comments, dependent: :destroy

  delegate :name, to: :category, prefix: :category

  mount_uploader :image, PictureUploader
  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :description, presence: true, length: {maximum: Settings.description_max}
  validate  :picture_size

  scope :starts_with, ->(name){where "name like ?", "%#{name}%"}
  scope :order_price, ->{order(price: :desc)}
  scope :load_product_by_ids, ->(product_ids){where id: product_ids}
  scope :order_name, ->(order){order(name: order)}
  scope :min_max_price, ->(min, max){where("price >= ? AND price <= ?", min, max)}
  scope :by_category, ->(cate_ids){where category_id: cate_ids if cate_ids}
  scope :newest, ->{order(create_at: :desc)}

  private

  def picture_size
    return unless image.size > Settings.max_image_size.megabytes
    errors.add :image, I18n.t("image_size")
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < AdminController
    load_and_authorize_resource param_method: :product_params

    def index
      @products = Product.includes(:category)
        .order_price.paginate page: params[:page], per_page: Settings.product_per_page
    end

    def show; end

    def new; end

    def edit; end

    def create
      @product = Product.new product_params
      if @product.save
        flash[:info] = t "admin.create_product"
        redirect_to @product
      else
        render :new
      end
    end

    def update
      if @product.update_attributes product_params
        flash[:success] = t "sucess_msg"
        redirect_to admin_products_path
      else
        render :edit
      end
    end

    def destroy
      if @product.destroy
        flash[:success] = t ".product_deleted_msg"
      else
        flash[:danger] = t ".product_delete_err_msg"
      end
      redirect_to admin_products_path
    end

    private

    def product_params
      params.require(:product).permit :name, :price, :description, :quantity, :image, :category_id
    end

    def load_categories
      @categories = Category.order_name :desc
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource
  before_action :load_products, only: :filter_product
  after_action :load_comments, :load_ratings, only: :show

  def index
    @products = @q.result.order_price
      .paginate page: params[:page], per_page: Settings.product_per_page
    @categories =  Category.includes(:subcategories).order_name
  end

  def show
    @comment = current_user.comments.build
    @rating = current_user.ratings.build
  end

  def filter_product; end

  private

  def load_products
    case
    when params[:cat_id]
      @products = Product.by_category params[:cat_id]
    when params[:sort_by]
      @products  = Product.order_name params[:sort_by].to_sym
    else params[:price_min][:value] && params[:price_max][:value]
      @products  = Product.min_max_price params[:price_min][:value], params[:price_max][:value]
    end
  end

  def load_comments
    @comments = @product.comments.includes(:users)
      .paginate page: params[:page], per_page: Settings.paginate.comment_perpage
  end

  def load_ratings
    @ratings = @product.ratings.includes(:users)
  end
end

app/views/admin/products/_product.html.erb
<tr id="product-<%= product.id %>">
  <td class="product-image-small"><%= image_tag product.image.url %></td>
  <td><%= product.name %></td>
  <td><%= number_to_currency product.price %></td>
  <td><%= product.quantity %></td>
  <td><%= product.category_name %></td>
  <td align="center">
    <%= link_to edit_admin_product_path product do %>
      <i class="fa fa-pencil" aria-hidden="true"></i>
    <% end %>
    <%= link_to admin_product_path(product), method: :delete,
      remote: true, data:{confirm: t(".sure")} do %>
      <i class="fa fa-trash-o" aria-hidden="true"></i>
    <% end %>
  </td>
</tr>

app/views/admin/products/edit.html.erb
<% provide :title,  t(".page_title") %>

<div class="panel panel-default panel-table">
  <div class="panel-heading">
    <div class="row">
      <div class="col col-xs-6">
        <h3 class="panel-title"><%= t ".panel_title" %></h3>
      </div>
    </div>
  </div>
  <div class="panel-body ">
    <div class="row">
      <div class="col-md-8">
        <%= form_for [:admin, @product], html: {multipart: true} do |f| %>
          <div class="form-group">
            <%= f.label :name, t(".name") %>
            <%= f.text_field :name, class: "form-control" %>
          </div>

          <div class="form-group d-flex">
            <div>
              <%= f.label :price, t("carts.price") %>
              <%= f.number_field :price, class: "form-control" %>
            </div>
            <div class="mg-left-20">
              <%= f.label :quantity, t("carts.quantity") %>
              <%= f.number_field :quantity, class: "form-control" %>
            </div>
          </div>
          <div class="d-flex">
            <div class="form-group">
              <%= f.label :image, t("products.edit.add_image") %>
              <%= f.file_field :image, class: "form-control"  %>
            </div>

            <div class="form-group mg-left-20">
              <%= f.label :category_id %>
              <%= f.collection_select :category_id, @categories, :id, :name,
                {prompt: true}, {class: "form-control"} %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :description, t("products.desc") %>
            <%= f.text_area :description, class: "form-control" %>
          </div>

          <%= f.submit t(".button"), class: "btn btn-primary" %>
        <% end %>
      </div>
      <div class="col-md-4">
        <%= render "admin/shared/error_messages", object: @product %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
 <% provide :title, t(".page_title")%>

 <div class="panel panel-default panel-table">
  <div class="panel-heading">
    <div class="row">
      <div class="col col-xs-6">
        <h3 class="panel-title"><%= t ".panel_title" %></h3>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= will_paginate @products %>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <table class="table table-striped table-bordered table-list">
      <thead>
        <tr>
          <th><%= t "product_image" %></th>
          <th><%= t ".name" %></th>
          <th><%= t ".price" %></th>
          <th><%= t ".quantity" %></th>
          <th><%= t "category" %></th>
          <th><em class="fa fa-cog"></em></th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "product", collection: @products, as: :product %>
      </tbody>
    </table>

  </div>
  <div class="panel-footer">
    <div class="row">
      <div class="col col-xs-4">
        <%= page_entries_info @products %>
      </div>
      <div class="col col-xs-8">
        <%= will_paginate @products %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<% provide :title,  t(".page_title") %>

<div class="panel panel-default panel-table">
  <div class="panel-heading">
    <div class="row">
      <div class="col col-xs-6">
        <h3 class="panel-title"><%= t ".panel_title" %></h3>
      </div>
    </div>
  </div>
  <div class="panel-body ">
  <div class="row">
    <div class="col-md-8">
    <%= form_for [:admin, @product], html: {multipart: true} do |f| %>
      <div class="form-group">
        <%= f.label :name, t(".name") %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group d-flex">
        <div>
          <%= f.label :price, t("carts.price") %>
          <%= f.number_field :price, class: "form-control" %>
        </div>
        <div class="mg-left-20">
          <%= f.label :quantity, t("carts.quantity") %>
          <%= f.number_field :quantity, class: "form-control" %>
        </div>
      </div>
      <div class="d-flex">
        <div class="form-group">
          <%= f.label :image, t("products.edit.add_image") %>
          <%= f.file_field :image, class: "form-control"  %>
        </div>

        <div class="form-group mg-left-20">
          <%= f.label :category_id %>
          <%= f.collection_select :category_id, @categories, :id, :name,
            {prompt: true}, {class: "form-control"} %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :description, t("products.desc") %>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <%= f.submit t(".button"), class: "btn btn-primary" %>
    <% end %>
    </div>
    <div class="col-md-4">
      <%= render "admin/shared/error_messages", object: @product %>
    </div>
  </div>
  </div>
</div>