config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :sessions,
    controllers: {registrations: "users",
                  sessions: "sessions",
                  omniauth_callbacks: "omniauth_callbacks"}
  as :user do
    get "login", to: "sessions#new", as: :new_user_session
    post "login", to: "sessions#create", as: :user_session
    delete "logout", to: "devise/sessions#destroy", as: :destroy_user_session
  end
  root "static_pages#home"
  get "/fetch_items", to: "products#filter_product", as: "fetch_items"
  resources :categories
  resources :products, only: %i(index show) do
    resources :comments
    resources :ratings, only: :create
    collection do
      match "search" => "products#index", via: [:get, :post], as: :search
    end
  end
  resources :orders do
    resources :order_details, only: :index
  end
  namespace :admin do
    root "static_pages#home"
    resources :users
    resources :categories do
      resources :products
    end
    resources :products
    resources :orders do
      resources :order_details
    end
  end
  resources :carts, only: :index
  get "add_cart/:id_product", to: "carts#add_cart", as: :add_cart
  get "remove_cart/:id_product", to: "carts#remove_cart", as: :remove_cart
  put "orders/:id_order", to: "orders#cancel", as: :cancel
  put "update_hard_cart", to: "carts#update_hard_cart", as: :update_hard_cart
end

app/models/product.rb
class Product < ApplicationRecord
  acts_as_paranoid
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
  attr_accessor :quantity_in_cart
  belongs_to :category
  has_many :order_details
  has_many :orders, through: :order_details
  has_many :ratings, dependent: :destroy
  has_many :comments, dependent: :destroy

  delegate :name, to: :category, prefix: :category

  mount_uploader :image, PictureUploader
  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :description, presence: true, length: {maximum: Settings.description_max}
  validate  :picture_size

  scope :starts_with, ->(name){where "name like ?", "%#{name}%"}
  scope :order_price, ->{order(price: :desc)}
  scope :load_product_by_ids, ->(product_ids){where id: product_ids}
  scope :order_name, ->(order){order(name: order)}
  scope :min_max_price, ->(min, max){where("price >= ? AND price <= ?", min, max)}
  scope :by_category, ->(cate_ids){where category_id: cate_ids if cate_ids}
  scope :newest, ->{order(create_at: :desc)}

  private

  def picture_size
    return unless image.size > Settings.max_image_size.megabytes
    errors.add :image, I18n.t("image_size")
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < AdminController
    load_and_authorize_resource param_method: :product_params

    def index
      @products = Product.includes(:category)
        .order_price.paginate page: params[:page], per_page: Settings.product_per_page
    end

    def show; end

    def new; end

    def edit; end

    def create
      @product = Product.new product_params
      if @product.save
        flash[:info] = t "admin.create_product"
        redirect_to @product
      else
        render :new
      end
    end

    def update
      if @product.update_attributes product_params
        flash[:success] = t "sucess_msg"
        redirect_to admin_products_path
      else
        render :edit
      end
    end

    def destroy
      if @product.destroy
        flash[:success] = t ".product_deleted_msg"
      else
        flash[:danger] = t ".product_delete_err_msg"
      end
      redirect_to admin_products_path
    end

    private

    def product_params
      params.require(:product).permit :name, :price, :description, :quantity, :image, :category_id
    end

    def load_categories
      @categories = Category.order_name :desc
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource
  before_action :load_products, only: :filter_product
  after_action :load_comments, :load_ratings, only: :show

  def index
    @products = @q.result.order_price
      .paginate page: params[:page], per_page: Settings.product_per_page
    @categories =  Category.includes(:subcategories).order_name
  end

  def show
    @comment = current_user.comments.build
    @rating = current_user.ratings.build
  end

  def filter_product; end

  private

  def load_products
    case
    when params[:cat_id]
      @products = Product.by_category params[:cat_id]
    when params[:sort_by]
      @products  = Product.order_name params[:sort_by].to_sym
    else params[:price_min][:value] && params[:price_max][:value]
      @products  = Product.min_max_price params[:price_min][:value], params[:price_max][:value]
    end
  end

  def load_comments
    @comments = @product.comments.includes(:users)
      .paginate page: params[:page], per_page: Settings.paginate.comment_perpage
  end

  def load_ratings
    @ratings = @product.ratings.includes(:users)
  end
end

app/views/products/_product.html.erb
<article class="product-item-wrap col-md-4 col-sm-6">
  <div class="product-item-inner">
    <div class="product-thumb">
      <%= link_to product_path(product) do %>
        <%= image_tag "product-53.jpg", class: "product-image" %>
      <% end %>
    </div>
    <div class="product-info">
      <h4 class="product-title"><%= product.name %></h4>
      <span class="price"><%= number_to_currency product.price %></span>
    </div>
    <div class="product-action">
      <%= link_to t("add_to_card"), add_cart_path(product), remote: true,
        method: :get, class: "btn-accent add-to-card" %>
    </div>
 </div>
</article>

app/views/products/_sidebar_menu.html.erb
<%= search_form_for @q do |f|  %>
  <%= f.search_field :name_cont %>
  <%= f.submit name: nil, class: "mg-top-20 btn-primary btn" %>
<% end %>

<div class="widget">
  <h4 class="widget-title"><%= t "sort_name" %></h4>
  <%= form_tag({controller: "products", action: "filter_product"}, remote: true,  method: "get") do %>
    <%= select_tag :sort_by, options_for_select([[t("sort_name_asc"), "asc"],
      [t("sort_name_desc"), "desc"]]) %>
    <%= submit_tag t("submit_btn"), name: nil, class: "btn btn-primary" %>
  <% end %>
</div>

<div class="widget">
  <h4 class="widget-title"><%= t "category" %></h4>
  <%= render partial: "categories/category", collection: @categories, as: :category %>
</div>

<div class="widget">
  <p>
    <label for="amount"><%= t "sort_price" %></label>
    <input type="text" id="amount" readonly>
  </p>
  <div id="the_slider"></div>
  <%= form_tag({controller: "products", action: "filter_product"}, remote: true, id: "ranger-price", method: "get") do %>
    <%= hidden_field :price_min, :value %>
    <%= hidden_field :price_max, :value %>
    <p class= "price-ranger"></p>
    <%= submit_tag t("submit_btn"), name: nil, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/products/filter_product.js.erb
$('.products-wrap').html('<%= escape_javascript(render partial: "product", collection: @products, as: :product) %>');

app/views/products/index.html.erb
<% provide :page_title, t("product")%>
<div class="products-wrapper row">
  <div class="products-wrap d-flex col-md-10">
    <%= render partial: "product", collection: @products, as: :product %>
  </div>
  <div class="col-md-2">
    <%= render "sidebar_menu" %>
  </div>
</div>

app/views/products/show.html.erb
<% provide :page_title, @product.name %>
<div id="primary-content">
  <div class="products-single-wrapper clearfix">
    <div class="container">
      <div class="row clearfix">
        <div class="product-wrap">
          <div class="single-product-info d-flex">
            <div class="col-sm-5">
              <div class="single-product-image">
                <div class="single-product-main">
                  <%= image_tag("product-53.jpg", class: "product-main-image") %>
                </div>
              </div>
            </div>
            <div class="col-sm-7">
              <h3 class="product-title"><%= @product.name %></h3>
              <p class="product-rating">
                <% @product.rate_average.to_i.round.times do %>
                  <i class="fa fa-star"></i>
                <% end %>
              </p>
              <span class="product-price"><%= number_to_currency @product.price %></span>
              <p class="product-des">
                <%= @product.description %>
              </p>
              <div class="product-action">
                <div class="product-quantity">
                  <a class="fa fa-minus btn-number"></a>
                  <input type="text" step="1" min="1" max="" name="quantity" value="1" title="Qty" class="input-text qty text" size = "5">
                  <a class="fa fa-plus btn-number"></a>
                </div>
                <% if @product.quantity > Settings.product_min %>
                  <%= link_to t("add_to_card"), add_cart_path(@product), remote: true,
                    method: :get, class: "btn-accent add-to-card" %>
                <% else %>
                  <button class = "btn-accent add-to-card"><%= t "sold_out" %></button>
                <% end %>
              </div>
              <span class="category">
                <%= t "admin.products.index.category" %>
                <%= link_to @product.category.name, "#" %>
              </span>
              <div class="product-share">
                <span><%= t "share_text" %></span>
                <%= social_share_button_tag(@product.name) %>
              </div>
            </div>
          </div>
          <div class="box" id="comments">
            <h4 class="product-section-title"><%= t "comment_section" %></h4>
            <hr>
            <div class="comment-product">
              <%= render @product.comments %>
            </div>
            <% if can? :create, @comment %>
              <div class="comment-new">
                <h4 class="product-section-title"><%= t "leave_comment" %></h4>
                  <%= render  partial: "comments/form" %>
              </div>
            <% end %>
          </div>
          <div class="single-product-content justify-content-center d-flex">
            <div class="col-md-12">
              <div class="product-rating">
                <h3 class="product-section-title"><%= t "button_rate" %></h3>
                <div class="prodduct-rating">
                  <%= render @product.ratings %>
                  <% if can? :create, @rating %>
                    <%= render partial: "ratings/new" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>